### PR TITLE
Add error log producing test

### LINKED ISSUE #265: Add Linker test which creates an error log
Devise a test with a known issue in the linking, and ensure the error is properly remoted to the log

depends on #229

### PR DESCRIPTION
**Pull request by ksimpson-work**
close #265 

Todo added for adding nvjitlink backend test - related issue : 4902246

### CODE REVIEW

**Comment by ksimpson-work** [comment]
/ ok to test

File: cuda_core/tests/test_linker.py [hunk 1]
```diff
@@ -122,15 +122,28 @@ def test_linker_link_invalid_target_type(compile_ptx_functions):
...
-    log = linker.get_error_log()
-    assert isinstance(log, str)
+
+    replacement_kernel = """
+extern __device__ int Z();
+extern __device__ int C(int a, int b);
+__global__ void A() { int result = C(Z(), 1);}
+"""
+    dummy_program = Program(replacement_kernel, "c++", ProgramOptions(relocatable_device_code=True)).compile("ptx")
+    linker = Linker(dummy_program, compile_ptx_functions[1], compile_ptx_functions[2], options=options)
```
Comment (leofang) [inline cuda_core/tests/test_linker.py]: nit:
```suggestion
    linker = Linker(dummy_program, *(compile_ptx_functions[1:]), options=options)
```

File: cuda_core/tests/test_linker.py [hunk 2]
```diff
@@ -122,15 +122,28 @@ def test_linker_link_invalid_target_type(compile_ptx_functions):
...
+    try:
+        linker.link("cubin")
+
+    except:  # noqa E722
```
Comment (leofang) [inline cuda_core/tests/test_linker.py]: Q: Is it because we could raise multiple kinds of exceptions? If so we can capture all:
```python
except (exception1, exception2, ...):
```

File: cuda_core/tests/test_linker.py [hunk 3]
```diff
@@ -122,15 +122,28 @@ def test_linker_link_invalid_target_type(compile_ptx_functions):
...
+        if culink_backend:
+            assert log.rstrip("\x00") == "error   : Undefined reference to '_Z1Zv' in 'None_ptx'"
 
 
 def test_linker_get_info_log(compile_ptx_functions):
     options = LinkerOptions(arch=ARCH)
     linker = Linker(*compile_ptx_functions, options=options)
     linker.link("cubin")
     log = linker.get_info_log()
+    print(log)
```
Comment (leofang) [inline cuda_core/tests/test_linker.py]: let's remove this
```suggestion
```

File: cuda_core/tests/test_linker.py [hunk 4]
```diff
@@ -122,15 +122,28 @@ def test_linker_link_invalid_target_type(compile_ptx_functions):
...
+__global__ void A() { int result = C(Z(), 1);}
+"""
+    dummy_program = Program(replacement_kernel, "c++", ProgramOptions(relocatable_device_code=True)).compile("ptx")
+    linker = Linker(dummy_program, compile_ptx_functions[1], compile_ptx_functions[2], options=options)
+    try:
+        linker.link("cubin")
+
+    except:  # noqa E722
+        log = linker.get_error_log()
+        # TODO when 4902246 is addressed, we can update this to cover nvjitlink as well
```
Comment (leofang) [inline cuda_core/tests/test_linker.py:159]: let's keep the existing sanity check
```suggestion
        assert isinstance(log, str)
        # TODO when 4902246 is addressed, we can update this to cover nvjitlink as well
```

Comment (leofang) [reply cuda_core/tests/test_linker.py:159]: btw, it's wild that nvjitlink is not working here...

File: cuda_core/tests/test_linker.py [hunk 5]
```diff
@@ -126,10 +135,23 @@ def test_linker_link_invalid_target_type(compile_ptx_functions):
...
+extern __device__ int Z();
+extern __device__ int C(int a, int b);
+__global__ void A() { int result = C(Z(), 1);}
+"""
+    dummy_program = Program(replacement_kernel, "c++", ProgramOptions(relocatable_device_code=True)).compile("ptx")
+    linker = Linker(dummy_program, *(compile_ptx_functions[1:]), options=options)
+    try:
+        linker.link("cubin")
+
+    except (nvJitLinkError_, CUDAError):
```
Comment (leofang) [inline cuda_core/tests/test_linker.py]: Q: Shouldn't we also capture `nvJitLinkError` (the one from `cuda.bindings`)?

File: cuda_core/tests/test_linker.py (hunk 4 above)
Comment (leofang) [reply cuda_core/tests/test_linker.py:159]: Keep for a record: the nvJitLink bug was about nvJitLink flushing error logs to stderr instead of storing it for later retrieval:
```
__________________________________________________________ test_linker_get_error_log __________________________________________________________
------------------------------------------------------------ Captured stderr call -------------------------------------------------------------
@E@error   : Undefined reference to '_Z1Zv' in 'None_ptx'
```

**Review by leofang — APPROVED** [review]

File: cuda_core/tests/test_linker.py (hunk 5 above)
Comment (leofang) [reply cuda_core/tests/test_linker.py]: fixed in 8f075da

**Comment by leofang** [comment]
(re-run the failed tests due to #482/#483)
